# Generated by Django 3.2.6 on 2021-08-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20210819_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='second',
            new_name='seconds',
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musics', to='back.album'),
        ),
    ]
