# Generated by Django 3.2.6 on 2021-08-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_artist_expo_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryExpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galleryexpo', to='back.expo')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galleryexpo', to='back.gallery')),
            ],
            options={
                'db_table': 'galleryexpo',
            },
        ),
    ]
