# Generated by Django 3.2.6 on 2021-08-20 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_galleryexpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('corrente', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=400)),
                ('preco', models.FloatField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='art', to='back.artist')),
            ],
            options={
                'db_table': 'art',
            },
        ),
    ]
