# Generated by Django 3.2.6 on 2021-08-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('gostos', models.CharField(max_length=400)),
                ('interesses', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finaluser', to='back.user')),
            ],
            options={
                'db_table': 'FinalUser',
            },
        ),
    ]
